name: Deploy Daftar Front to Cloud Run

on:
  push:
    branches:
      - master
    types:
      - closed

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Extract App Version
        run: |
          APP_VERSION=$(jq -r .version package.json)
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV

      - name: Build Vue.js App
        run: npm run build

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Configure gcloud
        run: |
          gcloud auth configure-docker ${{ secrets.GAR_REGION }}-docker.pkg.dev
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Build and Tag Docker Image
        run: |
          docker build -t ${{ secrets.GAR_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/daftar-images/daftar-front:$APP_VERSION -f Dockerfile .
          docker tag "${{ secrets.GAR_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/daftar-images/daftar-front:$APP_VERSION" \
                     "${{ secrets.GAR_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/daftar-images/daftar-front:latest"

      - name: Push Docker Image to Google Artifact Registry
        run: |
          docker push ${{ secrets.GAR_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/daftar-images/daftar-front:$APP_VERSION
          docker push ${{ secrets.GAR_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/daftar-images/daftar-front:latest

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy daftar-front \
            --image ${{ secrets.GAR_REGION }}-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/daftar-images/daftar-front:$APP_VERSION \
            --platform managed \
            --region ${{ secrets.GAR_REGION }} \
            --allow-unauthenticated \
            --set-env-vars=VUE_APP_BASE_URL=${{ secrets.DAFTAR_BACK_URL }} \
            --memory=512Mi \
            --cpu=1 \
            --port=80
